# Generated by Django 2.0.13 on 2019-04-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='recipient',
            field=models.CharField(choices=[('Madhav Vyas', 'Madhav Vyas'), ('Nikita Kulkarni', 'Nikita Kulkarni'), ('CR', 'CR')], default='Madhav Vyas', max_length=25),
        ),
    ]
