# Generated by Django 2.0.13 on 2019-04-02 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suggestion', '0003_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='postno',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='suggestion.Post'),
            preserve_default=False,
        ),
    ]
