# Generated by Django 2.0.13 on 2019-04-03 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suggestion', '0004_reply_postno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suggestion.Post', unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='reply',
            name='postno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suggestion.Connect'),
        ),
    ]
