# Generated by Django 2.0.13 on 2019-04-03 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suggestion', '0005_auto_20190403_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connect',
            name='number',
        ),
        migrations.AddField(
            model_name='reply',
            name='approved_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reply',
            name='postno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='suggestion.Post'),
        ),
        migrations.DeleteModel(
            name='Connect',
        ),
    ]
